export default {
  version: '2018-04-04',
  // currentUser: {},
  enroll: {},
  selectConferenceMembersId: [],
  replacePeople: {},
  replaceList: [],
  userInfo: {},
  nowConferenceId: 0,
  journeyInfo: null,
  nowConferenceName: '',
  hotelId: '',
  hotelName: '',
  membersId: [],
  accomMemberList: [],
  accomValue: [],
  accomSelect: {},
  accomPic: {},
  allMembers: {},
  room: [],
  addPeopleMembers: [],
  isRoot: false,
  isUser: false,
  isAdmin: false,
  isDriver: false,
  val: false,
  firstTime: '',
  lastTime: '',
  roomArrs: []
}
