export default {
  version: '2018-04-04',
  currentUser: {},
  enroll: {},
  selectConferenceMembersId: [],
  replacePeople: {},
  replaceList: [],
  userInfo: {},
  nowConferenceId: 0,
  journeyInfo: null,
  nowConferenceName: '',
  hotelId: '',
  hotelName: '',
  membersId: [],
  accomMemberList: [],
  accomValue: [],
  accomSelect: {},
  accomPic: {},
  addInfo: null,
  room: [],
  addPeopleMembers: []
}
